In [2]:
w1, w2, w3 = 0.3, 0.3, 0.5

In [7]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [8]:
kanto_yield_apples = kanto_temp * w1+ kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

63.5

In [9]:
print("the expected yield of apples is {}".format(kanto_yield_apples))

the expected yield of apples is 63.5


represent the climate data for each reign as vector 

In [10]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

three number in each represent temp rainfall and humidity 

present set of wights as vector

In [3]:
weights = [w1, w2, w3]

write function crop_yield 

In [11]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    
    return result

In [12]:
crop_yield(kanto,weights)

63.5

In [11]:
crop_yield(johto,weights)

85.7

In [12]:
crop_yield(unova, weights)

84.5

Numpy arrays.
first convert list into numpy array then perform computation

In [13]:
import numpy as np

np.array function to create Numpy arrays

In [14]:
kanto = np.array([73, 67, 43])

In [15]:
kanto

array([73, 67, 43])

In [14]:
weights = np.array([w1, w2, w3])

Numpy array have the type ndarray

In [17]:
type(kanto)

numpy.ndarray

In [18]:
type(weights)

numpy.ndarray

In [21]:
weights[0]

0.3

In [22]:
weights[0]
weights[1]

0.3

In [23]:
weights[1]

0.3

In [24]:
weights[2]

0.5

In [25]:
weights[2]
weights[1]

0.3

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4, 5, 6])

corresponding elements get multiplied

In [27]:
arr1*arr2

array([ 4, 10, 18])

In [29]:
arr2.sum()

15

<h1>Multi-dimensional Numpy arrays </h1>

In [30]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

.shape function gives shape dimesion parameter

In [33]:
# 2d array matrix 
climate_data.shape

(5, 3)

In [35]:
weights.shape

(3,)

In [36]:
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

arr3.shape

(2, 2, 3)

All the element in numpy array have the same data type you can check it by using .dtype property

In [38]:
climate_data.dtype

dtype('int64')

In [39]:
weights.dtype

dtype('float64')

if any array contains even single floating point number then whole array will be converted to floats

we can now compute the predicted yield of apples in all region using single matrix multiplication between climate_data (5 X 3 matrix) and weights 

np.matmul function or @ to perform matrix multiplication

In [41]:
np.matmul(climate_data, weights)

array([63.5, 85.7, 95.3, 62. , 84.5])

In [42]:
climate_data @ weights

array([63.5, 85.7, 95.3, 62. , 84.5])

<h1> Working with CSV files</h1>

In [43]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fe2a80db9a0>)

In [44]:
climate_data = np.genfromtxt('climate.txt',delimiter=',', skip_header=1)

In [45]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [46]:
climate_data.shape

(10000, 3)

In [47]:
weights = np.array([0.3, 0.2, 0.5])

In [48]:
yields = climate_data @ weights

In [49]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [50]:
yields.shape

(10000,)

Add the yiels to climate_data as fourth column using np.concatenate function

In [52]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis =1)

In [53]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [54]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt = '%.2f',
           delimiter=',',
           header='temprature, rainfall, humidity, yield_apples')

In [55]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

<h2>Array broadcasting</h2>
allowing airthmatic operation between two arrays with different number of dimension but compatible shapes.

In [56]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [57]:
arr2.shape

(3, 4)

In [58]:
arr4 = np.array([4,5,6,7])

In [59]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])