In [1]:
import numpy as np

 <h5>numpy.array(object, dtype=None, copy=True, order=None,  subok=False, ndmin=0) </h5>
 It  creates  an  ndarray  from  any  object  exposing  array  interface,  or  from  any  method  that returns an array

 memory block holds the element in row major order

In [2]:

# minimum dimensions

a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [3]:
# dtype parameter 

a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


<b>Data Type Objects(dtype) </b>
A data type object describes the interpretation of fixed block of memory corresponding to an array depending on the following aspects:

> Type of data( int, float or python objec)
> size of data 
> Byte order (little endian or big endian)

A dtype object is constructed using following :

<b>numpy.dtype(object, align, copy)</b>

<b> Object:</b> To be converted to data type object 

<b> Align: </b> If true add padding to the field to make it similar to C struct 

<b> Copy:</b> Makes a new copy of dtype object. If False, the result is referece to built in data type 




In [4]:
# using array-scaler type 

dt = np.dtype(np.int32)
print(dt)

# using endian notation

dt = np.dtype('>i4')
print(dt)

int32
>i4


int8 -> i1,  int16 -> i2,  int32 -> i3,  int64 -> i4

In [14]:
# first create structured data type 

import numpy as np

dt = np.dtype([('age', np.int8)])
print(dt)
print(dt[0])

[('age', 'i1')]
int8


In [13]:
# now apply it to ndaray object 

dt = np.dtype([('age', np.int8)])

a = np.array([(10,), (20,), (30,)], dtype = dt)

print(a)

[(10,) (20,) (30,)]


<h3> Numpy Array Attributes</h3>


In [15]:
# ndarray.shape -> returns tupple consisting of array dimensions. Can also be used 
# to resize the array

a = np.array([[1,2,3], [4,5,6]])

print(a.shape)

(2, 3)


In [16]:
# this resizes the ndarray 

a = np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
# reshape function to resize the array 

a = np.array([[1,2,3],[4,5,6]])

b = a.reshape(3,2)

print(b)

[[1 2]
 [3 4]
 [5 6]]


<h4>ndarray.ndim</h4>
returns the number of array dimensions 

In [22]:

# an array of evenly spced numbers 

a = np.arange(24)

print(a)

a.ndim

# now reshape it 

b = a.reshape(2,4,3)

print(b)

# b is having three dim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


<h4> numpy.itemsize</h4>
returns the length of the each element of array in bytes.

In [25]:
# dtype of array is int8 (1 byte)

x = np.array([1,2,3,4,5], dtype = np.int8)

print(x.itemsize)

1


In [26]:
# dtype of array now is float32 (4 bytes)

x = np.array([1,2,3,4,5], dtype = np.float32)

print(x.itemsize)

4
